# Routes are in French but they can be modified
app_homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
app_search:
    path:     /recherche
    defaults: { _controller: "AppBundle:Default:search" }
app_elections:
    path:     /elections
    defaults: { _controller: "AppBundle:Default:elections" }
app_election:
    path:     /election/{id}/{name}
    defaults: { _controller: "AppBundle:Default:election" }
    requirements:
        id: '\d+'
app_election_department:
    path:     /election/{election_id}/departement/{department_id}/{name}
    defaults: { _controller: "AppBundle:Default:electionDepartment" }
    requirements:
        election_id: '\d+'
        department_id: '\d+'
app_election_department_by_code:
    path:     /election/{election_id}/departement/code/{department_code}/{name}
    defaults: { _controller: "AppBundle:Default:electionDepartment" }
    requirements:
        election_id: '\d+'
app_election_city:
    path:     /election/{election_id}/ville/{city_id}/{name}
    defaults: { _controller: "AppBundle:Default:electionCity" }
    requirements:
        election_id: '\d+'
        city_id: '\d+'
app_election_city_by_code:
    path:     /election/{election_id}/ville/code/{city_code}/{name}
    defaults: { _controller: "AppBundle:Default:electionCity" }
    requirements:
        election_id: '\d+'
app_election_district:
    path:     /election/{election_id}/circonscription/{district_id}/{name}
    defaults: { _controller: "AppBundle:Default:electionDistrict" }
    requirements:
        election_id: '\d+'
        district_id: '\d+'
app_election_district_city:
    path:     /election/{election_id}/circonscription/{district_id}/ville/{city_id}/{name}
    defaults: { _controller: "AppBundle:Default:electionDistrictCity" }
    requirements:
        election_id: '\d+'
        district_id: '\d+'
        city_id: '\d+'
app_department:
    path:     /departement/{id}/{name}
    defaults: { _controller: "AppBundle:Default:department" }
    requirements:
        id: '\d+'
app_candidate:
    path:     /candidat/{id}/{name}
    defaults: { _controller: "AppBundle:Default:candidate" }
    requirements:
        id: '\d+'
app_nuance:
    path:     /nuance/{id}/{name}
    defaults: { _controller: "AppBundle:Default:nuance" }
    requirements:
        id: '\d+'
app_city:
    path:     /ville/{id}/{name}
    defaults: { _controller: "AppBundle:Default:city" }
    requirements:
        id: '\d+'
app_contact:
    path:     /contact
    defaults: { _controller: "AppBundle:Default:contact" }
app_admin:
    path:     /admin/accueil
    defaults: { _controller: "AppBundle:Admin:index" }
app_admin_candidate:
    path:     /admin/candidat/{id}
    defaults: { _controller: "AppBundle:Admin:candidate" }
    requirements:
        id: '\d+'
app_admin_candidates:
    path:     /admin/candidats
    defaults: { _controller: "AppBundle:Admin:candidates" }
app_admin_elections:
    path:     /admin/elections
    defaults: { _controller: "AppBundle:Admin:elections" }
app_admin_election:
    path:     /admin/election/{id}
    defaults: { _controller: "AppBundle:Admin:election" }
    requirements:
        id: '\d+'
app_admin_nuances:
    path:     /admin/nuances
    defaults: { _controller: "AppBundle:Admin:nuances" }
app_admin_nuance:
    path:     /admin/nuance/{id}
    defaults: { _controller: "AppBundle:Admin:nuance" }